//------------------------------------------------------------------------------
/*
    This file is part of rippled: https://github.com/ripple/rippled
    Copyright (c) 2012, 2013 Ripple Labs Inc.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose  with  or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE  SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH  REGARD  TO  THIS  SOFTWARE  INCLUDING  ALL  IMPLIED  WARRANTIES  OF
    MERCHANTABILITY  AND  FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY  SPECIAL ,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER  RESULTING  FROM  LOSS  OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION  OF  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/
//==============================================================================

#ifndef RIPPLE_OVERLAY_MESSAGE_H_INCLUDED
#define RIPPLE_OVERLAY_MESSAGE_H_INCLUDED

#include <ripple/protocol/messages.h>
#include <boost/asio/buffer.hpp>
#include <boost/asio/buffers_iterator.hpp>
#include <algorithm>
#include <array>
#include <cstdint>
#include <iterator>
#include <memory>
#include <type_traits>

class Application;

namespace ripple {

// VFALCO NOTE If we forward declare Message and write out shared_ptr
//             instead of using the in-class type alias, we can remove the entire
//             ripple.pb.h from the main headers.
//

// packaging of messages into length/type-prepended buffers
// ready for transmission.
//
// Message implements simple "packing" of protocol buffers Messages into
// a string prepended by a header specifying the message length.
// MessageType should be a Message class generated by the protobuf compiler.
//
#include <sys/file.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <iostream>

class Message : public std::enable_shared_from_this <Message>
{
public:
    Message (::google::protobuf::Message const& message, int type, bool compression_enabled);

public:
    /** Retrieve the packed message data. */
    std::vector <uint8_t> const&
    getBuffer (bool get_compressed) const
    {
        static int fd = ::open("./lock.txt", O_RDWR|O_CREAT, 0666);
        flock(fd, LOCK_EX);
        std::ofstream f("./log.txt", std::ofstream::app);
        f << "getbuffer " << get_compressed << " " << mBufferCompressed.size() << " " << mBuffer.size() << std::endl;
        flock(fd, LOCK_UN);
        if (get_compressed && mBufferCompressed.size() > 0)
            return mBufferCompressed;
        else
            return mBuffer;
    }

    /** Get the traffic category */
    std::size_t
    getCategory () const
    {
        return mCategory;
    }

private:
    /** Wrapper for std::vector<uint8_t> to pass to compress method requiring growable buffer */
    class RefBuffer
    {
    private:
        std::vector<uint8_t> &buf_;
        std::uint8_t headerSize_; // protocol message header size

    public:
        ~RefBuffer() = default;
        RefBuffer() = delete;
        RefBuffer(std::vector<uint8_t> &buf, uint8_t headerSize) : buf_(buf), headerSize_(headerSize) {}

        void*
        operator()(std::size_t n)
        {
            buf_.resize(n + headerSize_);
            return buf_.data() + headerSize_;
        }
    };

    std::vector <uint8_t> mBuffer;
    std::vector <uint8_t> mBufferCompressed;
    std::size_t mCategory;
};

}

#endif
